name: "jail-${VPL_BASE_DISTRO:?error}-${VPL_INSTALL_LEVEL:?error}"
services:
  vpl-jail:
    image: "jail-${VPL_BASE_DISTRO:?error}-${VPL_INSTALL_LEVEL:?error}"
    privileged: "${VPL_RUN_PRIVILEGED:?error}"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VPL_BASE_DISTRO
        - VPL_INSTALL_LEVEL
        - VPL_JAIL_JAILPATH
        - VPL_JAIL_PORT
        - VPL_JAIL_SECURE_PORT
        - VPL_CERTIFICATES_DIR
        - VPL_JAIL_SSL_CERT_FILE
        - VPL_JAIL_SSL_KEY_FILE
    volumes:
      - type: bind
        source: ${VPL_HOST_SSL_DIRECTORY}
        target: ${VPL_CERTIFICATES_DIR}
        read_only: true
    ports:
      - "${VPL_EXPOSE_PORT}:${VPL_JAIL_PORT}"
      - "${VPL_EXPOSE_SECURE_PORT}:${VPL_JAIL_SECURE_PORT}"
