name: "jail-${VPL_BASE_DISTRO:?error}-${VPL_INSTALL_LEVEL:?error}+letsencrypt"
services:
  vpl-jail:
    image: "jail-${VPL_BASE_DISTRO:?error}-${VPL_INSTALL_LEVEL:?error}"
    privileged: "${VPL_RUN_PRIVILEGED:?error}"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.letsencrypt
      args:
        - VPL_BASE_DISTRO
        - VPL_INSTALL_LEVEL
        - VPL_JAIL_PORT
        - VPL_JAIL_SECURE_PORT
        - VPL_JAIL_JAILPATH
        - VPL_JAIL_SSL_CERT_FILE
        - VPL_JAIL_SSL_KEY_FILE
        - VPL_JAIL_CERTBOT_WEBROOT_PATH
        - VPL_SERVER_NAME
    volumes:
      - certbot_webroot:${VPL_JAIL_CERTBOT_WEBROOT_PATH}:ro
      - type: bind
        source: ${VPL_HOST_SSL_DIRECTORY}
        target: ${VPL_CERTIFICATES_DIR}
        read_only: true
    ports:
      - "80:${VPL_JAIL_PORT:?error}"
      - "${VPL_EXPOSE_SECURE_PORT}:${VPL_JAIL_SECURE_PORT}"
  
  certbot_obtain_certificate:
    image: vpl_certbot
    build:
      context: .
      dockerfile: Dockerfile.certbot
    command: "/bin/sh -c 'certbot certonly -n --webroot --webroot-path /var/www -m ${VPL_EMAIL_FOR_CERTBOT} --agree-tos -d ${VPL_SERVER_NAME}'"
    depends_on:
      vpl-jail:
        condition: service_started
    profiles: 
      - obtain_certificate
    volumes:
      - certbot_webroot:/var/www:rw
      - type: bind
        source: ${VPL_HOST_SSL_DIRECTORY}
        target: /etc/letsencrypt

  certbot_renew:
    environment:
      - VPL_HOST_SSL_DIRECTORY
    image: vpl_certbot
    build:
      context: .
      dockerfile: Dockerfile.certbot
    command: "/bin/sh -c 'trap exit TERM; echo \"Checking to renew certificates every 12h\"; while :; do certbot -q renew; sleep 12h & wait $!; done;'"
    depends_on:
      vpl-jail:
        condition: service_started
    volumes:
      - certbot_webroot:/var/www:rw
      - type: bind
        source: ${VPL_HOST_SSL_DIRECTORY}
        target: /etc/letsencrypt

volumes:
  certbot_webroot:
